from tkinter import *
window = Tk()
window .title('first')
window.geometry ("400x400")
label1 = Label(text='надпись1')
label1.grid(column=0,row=0)
label1 = Label(text='надпись2')
label1.grid(column=3,row=0)
button2 = Button(text='кнопка номер 1')
button1 = Button(text='кнопка номер 2')
entry1 = Entry(width=20)
entry1.grid()
text1 = Text(height=10,width=20)
text1.grid()
button1.grid(column=0,row=3)
button2.grid(column=3,row=3)
entry1.grid(column=1,row=2)
text1.grid(column=1,row=3)

window.mainloop()
